export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const ADD_POST_TO_FAVORITES = "ADD_POST_TO_FAVORITES";
export const REMOVE_POST_FROM_FAVORITES = "REMOVE_POST_FROM_FAVORITES";

export const SHOW_FAVORITES = "SHOW_FAVORITES";
export const SHOW_ALL = "SHOW_ALL";

export const SEARCH_POSTS = "SEARCH_POSTS";
